# Generated by Django 4.2.13 on 2024-10-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_notes',
            field=models.TextField(blank=True, null=True, verbose_name='User Notes'),
        ),
    ]
