# Generated by Django 4.2.13 on 2024-10-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Ex: example@example.com', max_length=255, verbose_name='Email Address'),
        ),
    ]
