# Generated by Django 4.2.13 on 2024-10-12 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealSlotTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(max_length=50, verbose_name='Slot Name')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Meal Slot Time',
                'verbose_name_plural': 'Meals Time',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True, verbose_name='Table Number')),
                ('is_available', models.BooleanField(default=True, verbose_name='Available')),
                ('adults', models.IntegerField(verbose_name='Adults')),
                ('children', models.IntegerField(verbose_name='Children')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables List',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Phone')),
                ('user_notes', models.TextField(blank=True, null=True, verbose_name='User Notes')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='Reservation Date')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('no_show', models.BooleanField(default=False, verbose_name='No Show')),
                ('slot_time_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bookings.mealslottime', verbose_name='Meal Slot')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.table', verbose_name='Table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservation List',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('stripe_payment_id', models.CharField(max_length=100, verbose_name='Stripe Payment ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Payment Date')),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Customer ID')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('PA', 'Paid'), ('F', 'Failed')], default='P', max_length=2, verbose_name='Status')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.reservation', verbose_name='Reservation')),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.table', verbose_name='Table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
