# Generated by Django 4.2.13 on 2024-09-23 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='l_name',
        ),
    ]
