# Generated by Django 4.2.13 on 2024-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_mealslottime_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealslottime',
            options={'verbose_name': 'Meal Slot Time', 'verbose_name_plural': 'Meal Slots'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
    ]
