# Generated by Django 4.2.13 on 2024-10-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_user_alter_reservation_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='payment_method_id',
        ),
    ]
