# Generated by Django 4.2.13 on 2024-10-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_reservation_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.TextField(),
        ),
    ]
