# Generated by Django 4.2.13 on 2024-09-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_user_id_payment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
