# Generated by Django 4.2.13 on 2024-10-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_stripe_payment_id_payment_payment_method_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='table_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.table', verbose_name='Table'),
        ),
    ]
