# Generated by Django 4.2.13 on 2024-10-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_mealslottime_options_alter_table_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealslottime',
            options={'verbose_name': 'Meal Slot Time', 'verbose_name_plural': 'Meals Time'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Table', 'verbose_name_plural': 'Tables List'},
        ),
    ]
