# Generated by Django 4.2.13 on 2024-10-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_mealslottime_options_alter_table_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='description',
        ),
    ]
