# Generated by Django 4.2.13 on 2024-10-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_reservation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.TextField(blank=True, null=True, verbose_name='Customer ID'),
        ),
    ]
