# Generated by Django 4.2.13 on 2024-10-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_payment_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_id',
            field=models.CharField(max_length=50, verbose_name='Stripe Payment ID'),
        ),
    ]
