XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
    BBBB BBBBBB
    BBBB BBBB
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XX
        XXXX XXXXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
        XXXX XXXX XXXXX XXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX X XXXX XXXXXXXXX X XXXXX XXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XX
        XXXXXXXBBBBB BBBBBBBBBBBBB BBBBBXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
        XXXX XXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBX XX
        XXXX XXXXXXXXX XXXXXX
        XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX
        BBBBB BBBBBBBB
        BBBBBBBB BBBBBBBB
    XXXXXXX
    XXXXX XXXXXXXXXX XXXXXXXXXXXXXX
        XXXX XXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX
            XXXX XXXXXXX XXXXXX XXXXXXXXX
            XX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXX XXXXX XXXXXXX
            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
                XXX XXXXXXXXXXXXXXXXXXX
                    XXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XX
                    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX

                XXXX XXXX XXXXXXX
                XXX XXXXXXXXXXXXXXXXX
                    XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXX
                        XXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXX
                        XXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXXXXXXXX
                        XXXXX
                        XXXX
                            XX XXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBXXXX XXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXX XXXXXXX
                        XXXXX
                    XXXXX
                XXXXX
                
            XXXXX
        XXXXXXXXX
        XXXX XXXXXXX XXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXXXXXXX XXX XXXXX
                    XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
                XXXXXX
            XXXXXX
            XXX XXXXXXXXXXXXXXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXXXXXXXX
                XXXXX
                XXXX
                    XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX gettext(u'Calendar') XXXXXXXXXXX
                XXXXX
            XXXXX
        XXXXXXXX
        XXXXX XXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                BBBBB BBBBBBBBBB
                BBBBBBBB BBBBBBBBBB
            XXXXXX
            BBBBB BBBBBBB
            BBBBBBBB BBBBBBB
        XXXXXXX
        XXXX XXXXXXXXX XXXXXXXXXXX XXX XXXXXXXXXXX XX XXXXXXX
        BBBBBBB BBBBBBBBBBBBBB
        BBBBB BBBBBBBBBBBB
        BBBBBBBB BBBBBBBBBBBB
    XXXXXXX
XXXXXXX
