BBBBBBB BBBBBBBBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB

BBBBB BBBBB
     X  gettext(u'TODOAPP  | ADMIN ') 
BBBBBBBB

BBBBB BBBBBBBBBB
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBXXX
BBBBBBBB

BBBBB BBBBBBBB
    XXX XXXXXXXXXXXXXXX gettext(u'Table Suite') XXXXX
BBBBBBBB

BBBBB BBBBBBBBBB
    XXXX XXXXXXXX XXXXXXXX XXXX XXX
    XXXXX XXXXXXXXBBB BBBBBBBBBBBBBBX XXXXXXXXXXXXXX
        BBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXX BB BBBBBBBBBBBBB BB BBBBXXXXXXXXBBBBBXXXXXXXXXXXXXXXXXX
        XXXXXXXXX
    XXXXXXX
BBBBBBBB
