# Generated by Django 4.2.13 on 2024-10-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmember',
            options={'verbose_name': 'Event Member', 'verbose_name_plural': 'Event Members'},
        ),
    ]
