BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXX XXXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBXX XXXXXXXX XXXX
            XX XXXXXXXXXX XXXXXXXX XXXXX XXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX XXXX XXXXX XXXX
        XXXXXX

        XXXX XXXXXXXXXXXXXXXXX
            XXXXXXXXX XXXXX XXXXX
            XXXXXXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
            XXXX
        XXXXXX
        XXXX
        XXXX XXXXXXXXXXXXXXXXX
            XXX XXXXXXXXXXXX X XXXXXXX XX XXXX XXXXXXXXXX
            XX XXXXXXXXXX XXXXXXXXXXX XXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBXX XXX XXXXXX XXXX
        XXXXXX
        XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXX
            XXXXXXX
                XXXX
                  XXX XXXXXXXXXXXXX XXXXXXXXXXXX
                  XXXXXXXXXXXXX
                  XXXXXXXXXXXXXXXXX
                  XXXXXXXXXXXXXX
                  XXXXXXXXXXXXXXX
                XXXXX
              XXXXXXXX
              XXXXXXX
                BBB BBBBBB BB BBBBBBBBBBB
                XXX XXXXXXXXXXX
                    XXXXXXXXX
                    XXXX XXXXX
                    XXXXXXXXX
                    XXXXXXXXX
                    XXXX
                        XX XXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBXXXXXXXXXXXX
                    XXXXX
                XXXXX
                BBBBBB
              XXXXXXXX
        XXXXXXXX
    XXXXXX
BBBBBBBB
