XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
BBBBBBB BBBBBBBBBBB

BBBBB BBBBB
XXXXX XXXXXX
BBBBBBBB

BBBBB BBBBBBB
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXX XXXXXXXXXXXXXXBBBBBBBBBB
        XXXXXX XXX XXXX XXX XXXX XX XXXXXX XXXX XXXXXXXXXX
        XXXXXXX XXXXXXXXXX XXXXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
BBBBBBBB BBBBBBB
