BBBBBBB BBBBBBBBBBBBBBBB
BBBB BBBBBB
BBBB BBBB

BBBBB BBBBBXXXXX XXXXXXXXXBBBBBBBB BBBBB

BBBBB BBBBBBBBBB
    XXXXX
        XXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX gettext(u'Dashboard') XXXXX
    XXXXXX
    XXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX gettext(u'Dashboard') XXXXXXXXX
    XXXXX
BBBBBBBB BBBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXXXX
            XX XXXXXXXXXXX XX XXXXXXXXXXXXXX XXXXXXXXXXX
            XXXX XXXXXXXXXXXXX
                XXXX gettext(u'TotalReservations') XXXXX
                XXXXXXXXXXXXXX
            XXXXXX
        XXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXX XXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
                    XXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX
                        XXXX XXXXXXXXXXXX
                            XXXX XXXXXXXXXXXXXXXXXX
                                XXXXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                    XXXXXXX
                                        XXX XXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'CustomerName') XXXXX
                                            XXX XXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XX XXXX XXXXXX XXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXX gettext(u'ReservationDate') XXXXX
                                           XXXXX
                                    XXXXXXXX
                                    XXXXXXX
                                        BBB BBBBBBBBBBB BB BBBBBBBBBBBBBBBBBB
                                            XXX XXXXXXXXXX XXXXXXXXXXXX
                                                XXX XXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXXXXXX
                                                XXXXXXXXX
                                            XXXXX
                                        BBBBBB
                                    XXXXXXXX
                                XXXXXXXX
                            XXXXXX
                        XXXXXX
                    XXXXXX
                XXXXXX
            XXXXXX
        XXXXXX
    XXXXXX

XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBBBBBB
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
BBBBBBBB BBBBBBBBBBBB
